/*
 * generated by Xtext 2.28.0
 */
package org.uppaal.ide;

import org.uppaal.ide.AbstractUppaalXMLIdeModule;

/**
 * Use this class to register ide components.
 */
public class UppaalXMLIdeModule extends AbstractUppaalXMLIdeModule {
}
