/*
 * generated by Xtext 2.28.0
 */
package org.uppaal.serializer;

import org.uppaal.serializer.AbstractUppaalXMLSemanticSequencer;

public class UppaalXMLSemanticSequencer extends AbstractUppaalXMLSemanticSequencer {
}
