/*
 * generated by Xtext 2.28.0
 */
package org.uppaal;

import org.eclipse.ocl.pivot.utilities.PivotStandaloneSetup;
import org.eclipse.ocl.xtext.completeocl.CompleteOCLStandaloneSetup;
import org.uppaal.UppaalXMLStandaloneSetupGenerated;
import org.uppaal.model.core.CorePackage;
import org.uppaal.model.declarations.DeclarationsPackage;
import org.uppaal.model.declarations.global.GlobalPackage;
import org.uppaal.model.declarations.system.SystemPackage;
import org.uppaal.model.expressions.ExpressionsPackage;
import org.uppaal.model.queries.QueriesPackage;
import org.uppaal.model.statements.StatementsPackage;
import org.uppaal.model.templates.TemplatesPackage;
import org.uppaal.model.types.TypesPackage;
import org.uppaal.model.visuals.VisualsPackage;

import com.google.inject.Injector;
import static org.eclipse.emf.ecore.EPackage.Registry.INSTANCE;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UppaalXMLStandaloneSetup extends UppaalXMLStandaloneSetupGenerated {

	public static void doSetup() {
		// Initialize OCL
		PivotStandaloneSetup.doSetup();
		CompleteOCLStandaloneSetup.doSetup();
		
		new UppaalXMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public void register(Injector injector) {
		// Core components
		INSTANCE.computeIfAbsent(UppaalPackage.eNS_URI, uri -> UppaalPackage.eINSTANCE);
		INSTANCE.computeIfAbsent(CorePackage.eNS_URI, uri -> CorePackage.eINSTANCE);
		INSTANCE.computeIfAbsent(TypesPackage.eNS_URI, uri -> TypesPackage.eINSTANCE);
		INSTANCE.computeIfAbsent(TemplatesPackage.eNS_URI, uri -> TemplatesPackage.eINSTANCE);

		// Language components
		INSTANCE.computeIfAbsent(DeclarationsPackage.eNS_URI, uri -> DeclarationsPackage.eINSTANCE);
		INSTANCE.computeIfAbsent(SystemPackage.eNS_URI, uri -> SystemPackage.eINSTANCE);
		INSTANCE.computeIfAbsent(GlobalPackage.eNS_URI, uri -> GlobalPackage.eINSTANCE);
		
		INSTANCE.computeIfAbsent(ExpressionsPackage.eNS_URI, uri -> ExpressionsPackage.eINSTANCE);
		INSTANCE.computeIfAbsent(QueriesPackage.eNS_URI, uri -> QueriesPackage.eINSTANCE);
		INSTANCE.computeIfAbsent(StatementsPackage.eNS_URI, uri -> StatementsPackage.eINSTANCE);
		
		// Template visuals
		INSTANCE.computeIfAbsent(VisualsPackage.eNS_URI, uri -> VisualsPackage.eINSTANCE);
		
		super.register(injector);
	}
}
