/*
 * generated by Xtext 2.28.0
 */
package org.muml.uppaal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UppaalXMLUiModule extends AbstractUppaalXMLUiModule {

	public UppaalXMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
