/*
 * generated by Xtext 2.28.0
 */
package org.muml.uppaal.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.muml.uppaal.UppaalXMLRuntimeModule;
import org.muml.uppaal.UppaalXMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UppaalXMLIdeSetup extends UppaalXMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UppaalXMLRuntimeModule(), new UppaalXMLIdeModule()));
	}
	
}
