/*
 * generated by Xtext 2.28.0
 */
package org.uppaal.serializer;

import org.uppaal.serializer.AbstractUppaalXMLSyntacticSequencer;

public class UppaalXMLSyntacticSequencer extends AbstractUppaalXMLSyntacticSequencer {
}
