/*
 * generated by Xtext 2.28.0
 */
package org.muml.uppaal;

import org.muml.uppaal.conversion.UppaalValueConverter;
import org.muml.uppaal.scoping.UppaalLazyLinker;
import org.muml.uppaal.scoping.UppaalQualifiedNameProvider;
import org.muml.uppaal.serializer.UppaalTransientValueService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UppaalXMLRuntimeModule extends AbstractUppaalXMLRuntimeModule {
	@Override
	public Class<UppaalQualifiedNameProvider> bindIQualifiedNameProvider() {
		return UppaalQualifiedNameProvider.class;
	}
	 
	@Override
	public Class<UppaalLazyLinker> bindILinker() {
		return UppaalLazyLinker.class;
	}
	
	@Override
	public Class<UppaalValueConverter> bindIValueConverterService() {
		return UppaalValueConverter.class;
	}
	
	@Override
	public Class<UppaalTransientValueService> bindITransientValueService() {
		return UppaalTransientValueService.class;
	}
}
